apiVersion: v1
kind: Service
metadata:
  name: service-grafana-standalone
  labels:
    name: service-grafana-standalone
    role: service
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    name: grafana-standalone
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: grafana-standalone
spec:
  serviceName: "service-grafana-standalone"
  replicas: 1
  template:
    metadata:
      labels:
        name: grafana-standalone
        role: standalone
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:6.1.6
          securityContext:
            runAsUser: 0
          env:
            - name: GF_SERVER_DOMAIN
              value: "localhost"
            - name: GF_SERVER_ROOT_URL
              value: "http://localhost"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: volume-grafana-standalone
  volumeClaimTemplates:
    - metadata:
        name: volume-grafana-standalone
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
